version: '3.2'

services:
  todo-db:
    image: postgres:11
    container_name: todo-db
    ports:
      - "5434:5432"
    volumes:
        - todo-db-volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=todo-db

volumes:
  todo-db-volume: {}